on: [push, pull_request, workflow_dispatch]

name: Build #& Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.4
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (ATREUS42)
        run: west build -s zmk/app -b nice_nano -- -DSHIELD=atreus42 -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: ATREUS42 DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano.dts.pre.tmp
      - name: ATREUS42 Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 atreus42_nice_nano.uf2
      - name: Archive (ATREUS42)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: atreus42_nice_nano.uf2
  # release:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Create release
  #     uses: ralphie02/zmk-config@master
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   - name: Create Github release
  #     uses:
